# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "say_goodbye": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "GoodBye": "00_core.ipynb",
         "o": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Muhammad-Ali.github.io/nbdev_experimentation/"

git_url = "https://github.com/Muhammad-Ali/nbdev_experimentation/tree/master/"

def custom_doc_links(name): return None
