# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'say_goodbye', 'HelloSayer', 'GoodBye', 'o']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
def say_goodbye(to):
    "Say hello to somebody"
    return f'Good-Bye {to}!'

# Cell
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to

    def say(self):
        "Do the saying"
        return say_hello(self.to)


# Cell
class GoodBye:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to

    def say(self):
        "Do the saying"
        return say_goodbye(self.to)


# Cell
o = HelloSayer("Alexis")
o.say()